stages:
  - build

variables:
  MAVEN_OPTS: ""
  MAVEN_CLI_OPTS: ""

# Use Maven + OpenJDK 17 image from Docker Hub
default:
  image: maven:3.9.6-eclipse-temurin-17

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS package --file pom.xml
