
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "AccelerationConfidence" )]
    public class AccelerationConfidence: IASN1PreparedElement {
            
            public static readonly AccelerationConfidence PointOneMeterPerSecSquared = new(1);
            public static readonly AccelerationConfidence OutOfRange = new(101);
            public static readonly AccelerationConfidence Unavailable = new(102);

            private int val;

            [ASN1Integer( Name = "AccelerationConfidence" )]
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 102L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public AccelerationConfidence() {
            }

            public AccelerationConfidence(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(AccelerationConfidence));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
