
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "AccidentSubCauseCode" )]
    public class AccidentSubCauseCode: IASN1PreparedElement {
            
            public static readonly AccidentSubCauseCode Unavailable = new(0);
            public static readonly AccidentSubCauseCode MultiVehicleAccident = new(1);
            public static readonly AccidentSubCauseCode HeavyAccident = new(2);
            public static readonly AccidentSubCauseCode AccidentInvolvingLorry = new(3);
            public static readonly AccidentSubCauseCode AccidentInvolvingBus = new(4);
            public static readonly AccidentSubCauseCode AccidentInvolvingHazardousMaterials = new(5);
            public static readonly AccidentSubCauseCode AccidentOnOppositeLane = new(6);
            public static readonly AccidentSubCauseCode UnsecuredAccident = new(7);
            public static readonly AccidentSubCauseCode AssistanceRequested = new(8);

            private int val;

            [ASN1Integer( Name = "AccidentSubCauseCode" )]
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 255L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public AccidentSubCauseCode() {
            }

            public AccidentSubCauseCode(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(AccidentSubCauseCode));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
