
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "ActionID", IsExtensible = false, IsSet = false)]
    public class ActionID : IASN1PreparedElement {
                
	private StationID originatingStationID_ ;
	
        [ASN1Element ( Name = "originatingStationID", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public StationID OriginatingStationID
        {
            get { return originatingStationID_; }
            set { originatingStationID_ = value;  }
        }
        
                
          
	private SequenceNumber sequenceNumber_ ;
	
        [ASN1Element ( Name = "sequenceNumber", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public SequenceNumber SequenceNumber
        {
            get { return sequenceNumber_; }
            set { sequenceNumber_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ActionID));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
