
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "AdverseWeatherCondition_AdhesionSubCauseCode" )]
    public class AdverseWeatherCondition_AdhesionSubCauseCode: IASN1PreparedElement {
            
            public static readonly AdverseWeatherCondition_AdhesionSubCauseCode Unavailable = new(0);
            public static readonly AdverseWeatherCondition_AdhesionSubCauseCode HeavyFrostOnRoad = new(1);
            public static readonly AdverseWeatherCondition_AdhesionSubCauseCode FuelOnRoad = new(2);
            public static readonly AdverseWeatherCondition_AdhesionSubCauseCode MudOnRoad = new(3);
            public static readonly AdverseWeatherCondition_AdhesionSubCauseCode SnowOnRoad = new(4);
            public static readonly AdverseWeatherCondition_AdhesionSubCauseCode IceOnRoad = new(5);
            public static readonly AdverseWeatherCondition_AdhesionSubCauseCode BlackIceOnRoad = new(6);
            public static readonly AdverseWeatherCondition_AdhesionSubCauseCode OilOnRoad = new(7);
            public static readonly AdverseWeatherCondition_AdhesionSubCauseCode LooseChippings = new(8);
            public static readonly AdverseWeatherCondition_AdhesionSubCauseCode InstantBlackIce = new(9);
            public static readonly AdverseWeatherCondition_AdhesionSubCauseCode RoadsSalted = new(10);

            private int val;

            [ASN1Integer( Name = "AdverseWeatherCondition-AdhesionSubCauseCode" )]
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 255L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public AdverseWeatherCondition_AdhesionSubCauseCode() {
            }

            public AdverseWeatherCondition_AdhesionSubCauseCode(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(AdverseWeatherCondition_AdhesionSubCauseCode));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
