
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "Altitude", IsExtensible = false, IsSet = false)]
    public class Altitude : IASN1PreparedElement {
                
	private AltitudeValue altitudeValue_ ;
	
        [ASN1Element ( Name = "altitudeValue", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public AltitudeValue AltitudeValue
        {
            get { return altitudeValue_; }
            set { altitudeValue_ = value;  }
        }
        
                
          
	private AltitudeConfidence altitudeConfidence_ ;
	
        [ASN1Element ( Name = "altitudeConfidence", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public AltitudeConfidence AltitudeConfidence
        {
            get { return altitudeConfidence_; }
            set { altitudeConfidence_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Altitude));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
