
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "AltitudeConfidence", IsExtensible = false, NumRootElements = 16)]
    public class AltitudeConfidence : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "alt-000-01", HasTag = true , Tag = 0 )]
            alt_000_01 , 
            [ASN1EnumItem ( Name = "alt-000-02", HasTag = true , Tag = 1 )]
            alt_000_02 , 
            [ASN1EnumItem ( Name = "alt-000-05", HasTag = true , Tag = 2 )]
            alt_000_05 , 
            [ASN1EnumItem ( Name = "alt-000-10", HasTag = true , Tag = 3 )]
            alt_000_10 , 
            [ASN1EnumItem ( Name = "alt-000-20", HasTag = true , Tag = 4 )]
            alt_000_20 , 
            [ASN1EnumItem ( Name = "alt-000-50", HasTag = true , Tag = 5 )]
            alt_000_50 , 
            [ASN1EnumItem ( Name = "alt-001-00", HasTag = true , Tag = 6 )]
            alt_001_00 , 
            [ASN1EnumItem ( Name = "alt-002-00", HasTag = true , Tag = 7 )]
            alt_002_00 , 
            [ASN1EnumItem ( Name = "alt-005-00", HasTag = true , Tag = 8 )]
            alt_005_00 , 
            [ASN1EnumItem ( Name = "alt-010-00", HasTag = true , Tag = 9 )]
            alt_010_00 , 
            [ASN1EnumItem ( Name = "alt-020-00", HasTag = true , Tag = 10 )]
            alt_020_00 , 
            [ASN1EnumItem ( Name = "alt-050-00", HasTag = true , Tag = 11 )]
            alt_050_00 , 
            [ASN1EnumItem ( Name = "alt-100-00", HasTag = true , Tag = 12 )]
            alt_100_00 , 
            [ASN1EnumItem ( Name = "alt-200-00", HasTag = true , Tag = 13 )]
            alt_200_00 , 
            [ASN1EnumItem ( Name = "outOfRange", HasTag = true , Tag = 14 )]
            outOfRange , 
            [ASN1EnumItem ( Name = "unavailable", HasTag = true , Tag = 15 )]
            unavailable , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(AltitudeConfidence));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }


    }
            
}
