
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "BasicVehicleContainerHighFrequency", IsExtensible = false, IsSet = false)]
    public class BasicVehicleContainerHighFrequency : IASN1PreparedElement {
                
	private Heading heading_ ;
	
        [ASN1Element ( Name = "heading", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public Heading Heading
        {
            get { return heading_; }
            set { heading_ = value;  }
        }
        
                
          
	private Speed speed_ ;
	
        [ASN1Element ( Name = "speed", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public Speed Speed
        {
            get { return speed_; }
            set { speed_ = value;  }
        }
        
                
          
	private DriveDirection driveDirection_ ;
	
        [ASN1Element ( Name = "driveDirection", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public DriveDirection DriveDirection
        {
            get { return driveDirection_; }
            set { driveDirection_ = value;  }
        }
        
                
          
	private VehicleLength vehicleLength_ ;
	
        [ASN1Element ( Name = "vehicleLength", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public VehicleLength VehicleLength
        {
            get { return vehicleLength_; }
            set { vehicleLength_ = value;  }
        }
        
                
          
	private VehicleWidth vehicleWidth_ ;
	
        [ASN1Element ( Name = "vehicleWidth", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public VehicleWidth VehicleWidth
        {
            get { return vehicleWidth_; }
            set { vehicleWidth_ = value;  }
        }
        
                
          
	private LongitudinalAcceleration longitudinalAcceleration_ ;
	
        [ASN1Element ( Name = "longitudinalAcceleration", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public LongitudinalAcceleration LongitudinalAcceleration
        {
            get { return longitudinalAcceleration_; }
            set { longitudinalAcceleration_ = value;  }
        }
        
                
          
	private Curvature curvature_ ;
	
        [ASN1Element ( Name = "curvature", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public Curvature Curvature
        {
            get { return curvature_; }
            set { curvature_ = value;  }
        }
        
                
          
	private CurvatureCalculationMode curvatureCalculationMode_ ;
	
        [ASN1Element ( Name = "curvatureCalculationMode", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public CurvatureCalculationMode CurvatureCalculationMode
        {
            get { return curvatureCalculationMode_; }
            set { curvatureCalculationMode_ = value;  }
        }
        
                
          
	private YawRate yawRate_ ;
	
        [ASN1Element ( Name = "yawRate", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public YawRate YawRate
        {
            get { return yawRate_; }
            set { yawRate_ = value;  }
        }
        
                
          
	private AccelerationControl accelerationControl_ ;
	
        private bool  accelerationControl_present = false ;
	
        [ASN1Element ( Name = "accelerationControl", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public AccelerationControl AccelerationControl
        {
            get { return accelerationControl_; }
            set { accelerationControl_ = value; accelerationControl_present = true;  }
        }
        
                
          
	private LanePosition lanePosition_ ;
	
        private bool  lanePosition_present = false ;
	
        [ASN1Element ( Name = "lanePosition", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public LanePosition LanePosition
        {
            get { return lanePosition_; }
            set { lanePosition_ = value; lanePosition_present = true;  }
        }
        
                
          
	private SteeringWheelAngle steeringWheelAngle_ ;
	
        private bool  steeringWheelAngle_present = false ;
	
        [ASN1Element ( Name = "steeringWheelAngle", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public SteeringWheelAngle SteeringWheelAngle
        {
            get { return steeringWheelAngle_; }
            set { steeringWheelAngle_ = value; steeringWheelAngle_present = true;  }
        }
        
                
          
	private LateralAcceleration lateralAcceleration_ ;
	
        private bool  lateralAcceleration_present = false ;
	
        [ASN1Element ( Name = "lateralAcceleration", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public LateralAcceleration LateralAcceleration
        {
            get { return lateralAcceleration_; }
            set { lateralAcceleration_ = value; lateralAcceleration_present = true;  }
        }
        
                
          
	private VerticalAcceleration verticalAcceleration_ ;
	
        private bool  verticalAcceleration_present = false ;
	
        [ASN1Element ( Name = "verticalAcceleration", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public VerticalAcceleration VerticalAcceleration
        {
            get { return verticalAcceleration_; }
            set { verticalAcceleration_ = value; verticalAcceleration_present = true;  }
        }
        
                
          
	private PerformanceClass performanceClass_ ;
	
        private bool  performanceClass_present = false ;
	
        [ASN1Element ( Name = "performanceClass", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public PerformanceClass PerformanceClass
        {
            get { return performanceClass_; }
            set { performanceClass_ = value; performanceClass_present = true;  }
        }
        
                
          
	private CenDsrcTollingZone cenDsrcTollingZone_ ;
	
        private bool  cenDsrcTollingZone_present = false ;
	
        [ASN1Element ( Name = "cenDsrcTollingZone", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public CenDsrcTollingZone CenDsrcTollingZone
        {
            get { return cenDsrcTollingZone_; }
            set { cenDsrcTollingZone_ = value; cenDsrcTollingZone_present = true;  }
        }
        
                
  
        public bool isAccelerationControlPresent () {
            return this.accelerationControl_present == true;
        }
        
        public bool isLanePositionPresent () {
            return this.lanePosition_present == true;
        }
        
        public bool isSteeringWheelAnglePresent () {
            return this.steeringWheelAngle_present == true;
        }
        
        public bool isLateralAccelerationPresent () {
            return this.lateralAcceleration_present == true;
        }
        
        public bool isVerticalAccelerationPresent () {
            return this.verticalAcceleration_present == true;
        }
        
        public bool isPerformanceClassPresent () {
            return this.performanceClass_present == true;
        }
        
        public bool isCenDsrcTollingZonePresent () {
            return this.cenDsrcTollingZone_present == true;
        }
        

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(BasicVehicleContainerHighFrequency));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
