
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "BasicVehicleContainerLowFrequency", IsExtensible = false, IsSet = false)]
    public class BasicVehicleContainerLowFrequency : IASN1PreparedElement {
                
	private VehicleRole vehicleRole_ ;
	
        [ASN1Element ( Name = "vehicleRole", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public VehicleRole VehicleRole
        {
            get { return vehicleRole_; }
            set { vehicleRole_ = value;  }
        }
        
                
          
	private ExteriorLights exteriorLights_ ;
	
        [ASN1Element ( Name = "exteriorLights", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public ExteriorLights ExteriorLights
        {
            get { return exteriorLights_; }
            set { exteriorLights_ = value;  }
        }
        
                
          
	private PathHistory pathHistory_ ;
	
        [ASN1Element ( Name = "pathHistory", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public PathHistory PathHistory
        {
            get { return pathHistory_; }
            set { pathHistory_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(BasicVehicleContainerLowFrequency));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
