
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "BasicContainer", IsExtensible = true, IsSet = false)]
    public class BasicContainer : IASN1PreparedElement {
                
	private StationType stationType_ ;
	
        [ASN1Element ( Name = "stationType", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public StationType StationType
        {
            get { return stationType_; }
            set { stationType_ = value;  }
        }
        
                
          
	private ReferencePosition referencePosition_ ;
	
        [ASN1Element ( Name = "referencePosition", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public ReferencePosition ReferencePosition
        {
            get { return referencePosition_; }
            set { referencePosition_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(BasicContainer));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
