
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "CAM", IsExtensible = false, IsSet = false)]
    public class CAM : IASN1PreparedElement {
                
	private ItsPduHeader header_ ;
	
        [ASN1Element ( Name = "header", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public ItsPduHeader Header
        {
            get { return header_; }
            set { header_ = value;  }
        }
        
                
          
	private CoopAwareness cam_ ;
	
        [ASN1Element ( Name = "cam", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public CoopAwareness Cam
        {
            get { return cam_; }
            set { cam_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(CAM));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
