
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "CamParameters", IsExtensible = true, IsSet = false)]
    public class CamParameters : IASN1PreparedElement {
                
	private BasicContainer basicContainer_ ;
	
        [ASN1Element ( Name = "basicContainer", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public BasicContainer BasicContainer
        {
            get { return basicContainer_; }
            set { basicContainer_ = value;  }
        }
        
                
          
	private HighFrequencyContainer highFrequencyContainer_ ;
	
        [ASN1Element ( Name = "highFrequencyContainer", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public HighFrequencyContainer HighFrequencyContainer
        {
            get { return highFrequencyContainer_; }
            set { highFrequencyContainer_ = value;  }
        }
        
                
          
	private LowFrequencyContainer lowFrequencyContainer_ ;
	
        private bool  lowFrequencyContainer_present = false ;
	
        [ASN1Element ( Name = "lowFrequencyContainer", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public LowFrequencyContainer LowFrequencyContainer
        {
            get { return lowFrequencyContainer_; }
            set { lowFrequencyContainer_ = value; lowFrequencyContainer_present = true;  }
        }
        
                
          
	private SpecialVehicleContainer specialVehicleContainer_ ;
	
        private bool  specialVehicleContainer_present = false ;
	
        [ASN1Element ( Name = "specialVehicleContainer", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public SpecialVehicleContainer SpecialVehicleContainer
        {
            get { return specialVehicleContainer_; }
            set { specialVehicleContainer_ = value; specialVehicleContainer_present = true;  }
        }
        
                
  
        public bool isLowFrequencyContainerPresent () {
            return this.lowFrequencyContainer_present == true;
        }
        
        public bool isSpecialVehicleContainerPresent () {
            return this.specialVehicleContainer_present == true;
        }
        

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(CamParameters));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
