
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "CauseCodeType" )]
    public class CauseCodeType: IASN1PreparedElement {
            
            public static readonly CauseCodeType Reserved = new(0);
            public static readonly CauseCodeType TrafficCondition = new(1);
            public static readonly CauseCodeType Accident = new(2);
            public static readonly CauseCodeType Roadworks = new(3);
            public static readonly CauseCodeType AdverseWeatherCondition_Adhesion = new(6);
            public static readonly CauseCodeType HazardousLocation_SurfaceCondition = new(9);
            public static readonly CauseCodeType HazardousLocation_ObstacleOnTheRoad = new(10);
            public static readonly CauseCodeType HazardousLocation_AnimalOnTheRoad = new(11);
            public static readonly CauseCodeType HumanPresenceOnTheRoad = new(12);
            public static readonly CauseCodeType WrongWayDriving = new(14);
            public static readonly CauseCodeType RescueAndRecoveryWorkInProgress = new(15);
            public static readonly CauseCodeType AdverseWeatherCondition_ExtremeWeatherCondition = new(17);
            public static readonly CauseCodeType AdverseWeatherCondition_Visibility = new(18);
            public static readonly CauseCodeType AdverseWeatherCondition_Precipitation = new(19);
            public static readonly CauseCodeType SlowVehicle = new(26);
            public static readonly CauseCodeType DangerousEndOfQueue = new(27);
            public static readonly CauseCodeType VehicleBreakdown = new(91);
            public static readonly CauseCodeType PostCrash = new(92);
            public static readonly CauseCodeType HumanProblem = new(93);
            public static readonly CauseCodeType StationaryVehicle = new(94);
            public static readonly CauseCodeType EmergencyVehicleApproaching = new(95);
            public static readonly CauseCodeType HazardousLocation_DangerousCurve = new(96);
            public static readonly CauseCodeType CollisionRisk = new(97);
            public static readonly CauseCodeType SignalViolation = new(98);
            public static readonly CauseCodeType DangerousSituation = new(99);

            private int val;

            [ASN1Integer( Name = "CauseCodeType" )]
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 255L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public CauseCodeType() {
            }

            public CauseCodeType(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(CauseCodeType));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
