
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "CenDsrcTollingZone", IsExtensible = false, IsSet = false)]
    public class CenDsrcTollingZone : IASN1PreparedElement {
                
	private Latitude protectedZoneLatitude_ ;
	
        [ASN1Element ( Name = "protectedZoneLatitude", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public Latitude ProtectedZoneLatitude
        {
            get { return protectedZoneLatitude_; }
            set { protectedZoneLatitude_ = value;  }
        }
        
                
          
	private Longitude protectedZoneLongitude_ ;
	
        [ASN1Element ( Name = "protectedZoneLongitude", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public Longitude ProtectedZoneLongitude
        {
            get { return protectedZoneLongitude_; }
            set { protectedZoneLongitude_ = value;  }
        }
        
                
          
	private CenDsrcTollingZoneID cenDsrcTollingZoneID_ ;
	
        private bool  cenDsrcTollingZoneID_present = false ;
	
        [ASN1Element ( Name = "cenDsrcTollingZoneID", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public CenDsrcTollingZoneID CenDsrcTollingZoneID
        {
            get { return cenDsrcTollingZoneID_; }
            set { cenDsrcTollingZoneID_ = value; cenDsrcTollingZoneID_present = true;  }
        }
        
                
  
        public bool isCenDsrcTollingZoneIDPresent () {
            return this.cenDsrcTollingZoneID_present == true;
        }
        

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(CenDsrcTollingZone));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
