
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "ClosedLanes", IsExtensible = true, IsSet = false)]
    public class ClosedLanes : IASN1PreparedElement {
                
	private HardShoulderStatus hardShoulderStatus_ ;
	
        private bool  hardShoulderStatus_present = false ;
	
        [ASN1Element ( Name = "hardShoulderStatus", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public HardShoulderStatus HardShoulderStatus
        {
            get { return hardShoulderStatus_; }
            set { hardShoulderStatus_ = value; hardShoulderStatus_present = true;  }
        }
        
                
          
	private DrivingLaneStatus drivingLaneStatus_ ;
	
        [ASN1Element ( Name = "drivingLaneStatus", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public DrivingLaneStatus DrivingLaneStatus
        {
            get { return drivingLaneStatus_; }
            set { drivingLaneStatus_ = value;  }
        }
        
                
  
        public bool isHardShoulderStatusPresent () {
            return this.hardShoulderStatus_present == true;
        }
        

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ClosedLanes));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
