
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "CoopAwareness", IsExtensible = false, IsSet = false)]
    public class CoopAwareness : IASN1PreparedElement {
                
	private GenerationDeltaTime generationDeltaTime_ ;
	
        [ASN1Element ( Name = "generationDeltaTime", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public GenerationDeltaTime GenerationDeltaTime
        {
            get { return generationDeltaTime_; }
            set { generationDeltaTime_ = value;  }
        }
        
                
          
	private CamParameters camParameters_ ;
	
        [ASN1Element ( Name = "camParameters", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public CamParameters CamParameters
        {
            get { return camParameters_; }
            set { camParameters_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(CoopAwareness));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
