
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "CurvatureValue" )]
    public class CurvatureValue: IASN1PreparedElement {
            
            public static readonly CurvatureValue Straight = new(0);
            public static readonly CurvatureValue ReciprocalOf1MeterRadiusToRight = new(-30000);
            public static readonly CurvatureValue ReciprocalOf1MeterRadiusToLeft = new(30000);
            public static readonly CurvatureValue Unavailable = new(30001);

            private int val;

            [ASN1Integer( Name = "CurvatureValue" )]
            [ASN1ValueRangeConstraint ( Min = -30000L, Max = 30001L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public CurvatureValue() {
            }

            public CurvatureValue(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(CurvatureValue));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
