
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "Curvature", IsExtensible = false, IsSet = false)]
    public class Curvature : IASN1PreparedElement {
                
	private CurvatureValue curvatureValue_ ;
	
        [ASN1Element ( Name = "curvatureValue", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public CurvatureValue CurvatureValue
        {
            get { return curvatureValue_; }
            set { curvatureValue_ = value;  }
        }
        
                
          
	private CurvatureConfidence curvatureConfidence_ ;
	
        [ASN1Element ( Name = "curvatureConfidence", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public CurvatureConfidence CurvatureConfidence
        {
            get { return curvatureConfidence_; }
            set { curvatureConfidence_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Curvature));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
