
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "CurvatureConfidence", IsExtensible = false, NumRootElements = 8)]
    public class CurvatureConfidence : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "onePerMeter-0-00002", HasTag = true , Tag = 0 )]
            OnePerMeter_0_00002 , 
            [ASN1EnumItem ( Name = "onePerMeter-0-0001", HasTag = true , Tag = 1 )]
            OnePerMeter_0_0001 , 
            [ASN1EnumItem ( Name = "onePerMeter-0-0005", HasTag = true , Tag = 2 )]
            OnePerMeter_0_0005 , 
            [ASN1EnumItem ( Name = "onePerMeter-0-002", HasTag = true , Tag = 3 )]
            OnePerMeter_0_002 , 
            [ASN1EnumItem ( Name = "onePerMeter-0-01", HasTag = true , Tag = 4 )]
            OnePerMeter_0_01 , 
            [ASN1EnumItem ( Name = "onePerMeter-0-1", HasTag = true , Tag = 5 )]
            OnePerMeter_0_1 , 
            [ASN1EnumItem ( Name = "outOfRange", HasTag = true , Tag = 6 )]
            OutOfRange , 
            [ASN1EnumItem ( Name = "unavailable", HasTag = true , Tag = 7 )]
            Unavailable , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(CurvatureConfidence));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }


    }
            
}
