
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "DangerousGoodsContainer", IsExtensible = false, IsSet = false)]
    public class DangerousGoodsContainer : IASN1PreparedElement {
                
	private DangerousGoodsBasic dangerousGoodsBasic_ ;
	
        [ASN1Element ( Name = "dangerousGoodsBasic", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public DangerousGoodsBasic DangerousGoodsBasic
        {
            get { return dangerousGoodsBasic_; }
            set { dangerousGoodsBasic_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DangerousGoodsContainer));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
