
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "DangerousSituationSubCauseCode" )]
    public class DangerousSituationSubCauseCode: IASN1PreparedElement {
            
            public static readonly DangerousSituationSubCauseCode Unavailable = new(0);
            public static readonly DangerousSituationSubCauseCode EmergencyElectronicBrakeEngaged = new(1);
            public static readonly DangerousSituationSubCauseCode PreCrashSystemEngaged = new(2);
            public static readonly DangerousSituationSubCauseCode EspEngaged = new(3);
            public static readonly DangerousSituationSubCauseCode AbsEngaged = new(4);
            public static readonly DangerousSituationSubCauseCode AebEngaged = new(5);
            public static readonly DangerousSituationSubCauseCode BrakeWarningEngaged = new(6);
            public static readonly DangerousSituationSubCauseCode CollisionRiskWarningEngaged = new(7);

            private int val;

            [ASN1Integer( Name = "DangerousSituationSubCauseCode" )]
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 255L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public DangerousSituationSubCauseCode() {
            }

            public DangerousSituationSubCauseCode(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DangerousSituationSubCauseCode));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
