
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "DangerousEndOfQueueSubCauseCode" )]
    public class DangerousEndOfQueueSubCauseCode: IASN1PreparedElement {
            
            public static readonly DangerousEndOfQueueSubCauseCode Unavailable = new(0);
            public static readonly DangerousEndOfQueueSubCauseCode SuddenEndOfQueue = new(1);
            public static readonly DangerousEndOfQueueSubCauseCode QueueOverHill = new(2);
            public static readonly DangerousEndOfQueueSubCauseCode QueueAroundBend = new(3);
            public static readonly DangerousEndOfQueueSubCauseCode QueueInTunnel = new(4);

            private int val;

            [ASN1Integer( Name = "DangerousEndOfQueueSubCauseCode" )]
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 255L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public DangerousEndOfQueueSubCauseCode() {
            }

            public DangerousEndOfQueueSubCauseCode(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DangerousEndOfQueueSubCauseCode));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
