
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "DangerousGoodsBasic", IsExtensible = false, NumRootElements = 20)]
    public class DangerousGoodsBasic : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "explosives1", HasTag = true , Tag = 0 )]
            Explosives1 , 
            [ASN1EnumItem ( Name = "explosives2", HasTag = true , Tag = 1 )]
            Explosives2 , 
            [ASN1EnumItem ( Name = "explosives3", HasTag = true , Tag = 2 )]
            Explosives3 , 
            [ASN1EnumItem ( Name = "explosives4", HasTag = true , Tag = 3 )]
            Explosives4 , 
            [ASN1EnumItem ( Name = "explosives5", HasTag = true , Tag = 4 )]
            Explosives5 , 
            [ASN1EnumItem ( Name = "explosives6", HasTag = true , Tag = 5 )]
            Explosives6 , 
            [ASN1EnumItem ( Name = "flammableGases", HasTag = true , Tag = 6 )]
            FlammableGases , 
            [ASN1EnumItem ( Name = "nonFlammableGases", HasTag = true , Tag = 7 )]
            NonFlammableGases , 
            [ASN1EnumItem ( Name = "toxicGases", HasTag = true , Tag = 8 )]
            ToxicGases , 
            [ASN1EnumItem ( Name = "flammableLiquids", HasTag = true , Tag = 9 )]
            FlammableLiquids , 
            [ASN1EnumItem ( Name = "flammableSolids", HasTag = true , Tag = 10 )]
            FlammableSolids , 
            [ASN1EnumItem ( Name = "substancesLiableToSpontaneousCombustion", HasTag = true , Tag = 11 )]
            SubstancesLiableToSpontaneousCombustion , 
            [ASN1EnumItem ( Name = "substancesEmittingFlammableGasesUponContactWithWater", HasTag = true , Tag = 12 )]
            SubstancesEmittingFlammableGasesUponContactWithWater , 
            [ASN1EnumItem ( Name = "oxidizingSubstances", HasTag = true , Tag = 13 )]
            OxidizingSubstances , 
            [ASN1EnumItem ( Name = "organicPeroxides", HasTag = true , Tag = 14 )]
            OrganicPeroxides , 
            [ASN1EnumItem ( Name = "toxicSubstances", HasTag = true , Tag = 15 )]
            ToxicSubstances , 
            [ASN1EnumItem ( Name = "infectiousSubstances", HasTag = true , Tag = 16 )]
            InfectiousSubstances , 
            [ASN1EnumItem ( Name = "radioactiveMaterial", HasTag = true , Tag = 17 )]
            RadioactiveMaterial , 
            [ASN1EnumItem ( Name = "corrosiveSubstances", HasTag = true , Tag = 18 )]
            CorrosiveSubstances , 
            [ASN1EnumItem ( Name = "miscellaneousDangerousSubstances", HasTag = true , Tag = 19 )]
            MiscellaneousDangerousSubstances , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DangerousGoodsBasic));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }


    }
            
}
