
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "DangerousGoodsExtended", IsExtensible = false, IsSet = false)]
    public class DangerousGoodsExtended : IASN1PreparedElement {
                
	private DangerousGoodsBasic dangerousGoodsType_ ;
	
        [ASN1Element ( Name = "dangerousGoodsType", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public DangerousGoodsBasic DangerousGoodsType
        {
            get { return dangerousGoodsType_; }
            set { dangerousGoodsType_ = value;  }
        }
        
                
          
	private int unNumber_ ;
	[ASN1Integer( Name = "" )]
    [ASN1ValueRangeConstraint ( Min = 0L, Max = 9999L, IsExtensible = false) ]
	    
        [ASN1Element ( Name = "unNumber", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public int UnNumber
        {
            get { return unNumber_; }
            set { unNumber_ = value;  }
        }
        
                
          
	private bool elevatedTemperature_ ;
	[ASN1Boolean( Name = "" )]
    
        [ASN1Element ( Name = "elevatedTemperature", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public bool ElevatedTemperature
        {
            get { return elevatedTemperature_; }
            set { elevatedTemperature_ = value;  }
        }
        
                
          
	private bool tunnelsRestricted_ ;
	[ASN1Boolean( Name = "" )]
    
        [ASN1Element ( Name = "tunnelsRestricted", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public bool TunnelsRestricted
        {
            get { return tunnelsRestricted_; }
            set { tunnelsRestricted_ = value;  }
        }
        
                
          
	private bool limitedQuantity_ ;
	[ASN1Boolean( Name = "" )]
    
        [ASN1Element ( Name = "limitedQuantity", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public bool LimitedQuantity
        {
            get { return limitedQuantity_; }
            set { limitedQuantity_ = value;  }
        }
        
                
          
	private string emergencyActionCode_ ;
	
        private bool  emergencyActionCode_present = false ;
	[ASN1String( Name = "", 
        StringType =  UniversalTags.IA5String , IsUCS = false )][ASN1ValueRangeConstraint ( Min = 1L, Max = 24L, IsExtensible = false) ]
	    
        [ASN1Element ( Name = "emergencyActionCode", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public string EmergencyActionCode
        {
            get { return emergencyActionCode_; }
            set { emergencyActionCode_ = value; emergencyActionCode_present = true;  }
        }
        
                
          
	private string phoneNumber_ ;
	
        private bool  phoneNumber_present = false ;
	[ASN1String( Name = "", 
        StringType =  UniversalTags.IA5String , IsUCS = false )][ASN1ValueRangeConstraint ( Min = 1L, Max = 24L, IsExtensible = false) ]
	    
        [ASN1Element ( Name = "phoneNumber", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public string PhoneNumber
        {
            get { return phoneNumber_; }
            set { phoneNumber_ = value; phoneNumber_present = true;  }
        }
        
                
          
	private string companyName_ ;
	
        private bool  companyName_present = false ;
	[ASN1String( Name = "", 
        StringType =  UniversalTags.UTF8String , IsUCS = false )][ASN1ValueRangeConstraint ( Min = 1L, Max = 24L, IsExtensible = false) ]
	    
        [ASN1Element ( Name = "companyName", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public string CompanyName
        {
            get { return companyName_; }
            set { companyName_ = value; companyName_present = true;  }
        }
        
                
  
        public bool isEmergencyActionCodePresent () {
            return this.emergencyActionCode_present == true;
        }
        
        public bool isPhoneNumberPresent () {
            return this.phoneNumber_present == true;
        }
        
        public bool isCompanyNamePresent () {
            return this.companyName_present == true;
        }
        

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DangerousGoodsExtended));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
