
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "DeltaReferencePosition", IsExtensible = false, IsSet = false)]
    public class DeltaReferencePosition : IASN1PreparedElement {
                
	private DeltaLatitude deltaLatitude_ ;
	
        [ASN1Element ( Name = "deltaLatitude", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public DeltaLatitude DeltaLatitude
        {
            get { return deltaLatitude_; }
            set { deltaLatitude_ = value;  }
        }
        
                
          
	private DeltaLongitude deltaLongitude_ ;
	
        [ASN1Element ( Name = "deltaLongitude", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public DeltaLongitude DeltaLongitude
        {
            get { return deltaLongitude_; }
            set { deltaLongitude_ = value;  }
        }
        
                
          
	private DeltaAltitude deltaAltitude_ ;
	
        [ASN1Element ( Name = "deltaAltitude", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public DeltaAltitude DeltaAltitude
        {
            get { return deltaAltitude_; }
            set { deltaAltitude_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DeltaReferencePosition));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
