
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "DeltaLongitude" )]
    public class DeltaLongitude: IASN1PreparedElement {
            
            public static readonly DeltaLongitude OneMicrodegreeEast = new(10);
            public static readonly DeltaLongitude OneMicrodegreeWest = new(-10);
            public static readonly DeltaLongitude Unavailable = new(131072);

            private int val;

            [ASN1Integer( Name = "DeltaLongitude" )]
            [ASN1ValueRangeConstraint ( Min = -131071L, Max = 131072L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public DeltaLongitude() {
            }

            public DeltaLongitude(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DeltaLongitude));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
