
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "DeltaAltitude" )]
    public class DeltaAltitude: IASN1PreparedElement {
            
            public static readonly DeltaAltitude OneCentimeterUp = new(1);
            public static readonly DeltaAltitude OneCentimeterDown = new(-1);
            public static readonly DeltaAltitude Unavailable = new(12800);

            private int val;

            [ASN1Integer( Name = "DeltaAltitude" )]
            [ASN1ValueRangeConstraint ( Min = -12700L, Max = 12800L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public DeltaAltitude() {
            }

            public DeltaAltitude(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DeltaAltitude));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
