
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "DrivingLaneStatus") ]
    public class DrivingLaneStatus : IASN1PreparedElement {
    
            private BitString val = null;

            [ASN1BitString( Name = "DrivingLaneStatus") ]            
            [ASN1ValueRangeConstraint ( Min = 1L, Max = 14L, IsExtensible = false) ]
	    
            public BitString Value
            {
                get { return val; }
                set { val = value; }
            }            
            
            public DrivingLaneStatus() {
            }

            public DrivingLaneStatus(BitString value) {
                this.Value = value;
            }            


            public void initWithDefaults()
	    {
	    }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DrivingLaneStatus));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
