
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "EmergencyVehicleApproachingSubCauseCode" )]
    public class EmergencyVehicleApproachingSubCauseCode: IASN1PreparedElement {
            
            public static readonly EmergencyVehicleApproachingSubCauseCode Unavailable = new(0);
            public static readonly EmergencyVehicleApproachingSubCauseCode EmergencyVehicleApproaching = new(1);
            public static readonly EmergencyVehicleApproachingSubCauseCode PrioritizedVehicleApproaching = new(2);

            private int val;

            [ASN1Integer( Name = "EmergencyVehicleApproachingSubCauseCode" )]
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 255L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public EmergencyVehicleApproachingSubCauseCode() {
            }

            public EmergencyVehicleApproachingSubCauseCode(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(EmergencyVehicleApproachingSubCauseCode));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
