
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "EventPoint", IsExtensible = false, IsSet = false)]
    public class EventPoint : IASN1PreparedElement {
                
	private DeltaReferencePosition eventPosition_ ;
	
        [ASN1Element ( Name = "eventPosition", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public DeltaReferencePosition EventPosition
        {
            get { return eventPosition_; }
            set { eventPosition_ = value;  }
        }
        
                
          
	private PathDeltaTime eventDeltaTime_ ;
	
        private bool  eventDeltaTime_present = false ;
	
        [ASN1Element ( Name = "eventDeltaTime", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public PathDeltaTime EventDeltaTime
        {
            get { return eventDeltaTime_; }
            set { eventDeltaTime_ = value; eventDeltaTime_present = true;  }
        }
        
                
          
	private InformationQuality informationQuality_ ;
	
        [ASN1Element ( Name = "informationQuality", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public InformationQuality InformationQuality
        {
            get { return informationQuality_; }
            set { informationQuality_ = value;  }
        }
        
                
  
        public bool isEventDeltaTimePresent () {
            return this.eventDeltaTime_present == true;
        }
        

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(EventPoint));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
