
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "HazardousLocation_SurfaceConditionSubCauseCode" )]
    public class HazardousLocation_SurfaceConditionSubCauseCode: IASN1PreparedElement {
            
            public static readonly HazardousLocation_SurfaceConditionSubCauseCode Unavailable = new(0);
            public static readonly HazardousLocation_SurfaceConditionSubCauseCode Rockfalls = new(1);
            public static readonly HazardousLocation_SurfaceConditionSubCauseCode EarthquakeDamage = new(2);
            public static readonly HazardousLocation_SurfaceConditionSubCauseCode SewerCollapse = new(3);
            public static readonly HazardousLocation_SurfaceConditionSubCauseCode Subsidence = new(4);
            public static readonly HazardousLocation_SurfaceConditionSubCauseCode SnowDrifts = new(5);
            public static readonly HazardousLocation_SurfaceConditionSubCauseCode StormDamage = new(6);
            public static readonly HazardousLocation_SurfaceConditionSubCauseCode BurstPipe = new(7);
            public static readonly HazardousLocation_SurfaceConditionSubCauseCode VolcanoEruption = new(8);
            public static readonly HazardousLocation_SurfaceConditionSubCauseCode FallingIce = new(9);

            private int val;

            [ASN1Integer( Name = "HazardousLocation-SurfaceConditionSubCauseCode" )]
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 255L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public HazardousLocation_SurfaceConditionSubCauseCode() {
            }

            public HazardousLocation_SurfaceConditionSubCauseCode(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(HazardousLocation_SurfaceConditionSubCauseCode));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
