
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "HazardousLocation_ObstacleOnTheRoadSubCauseCode" )]
    public class HazardousLocation_ObstacleOnTheRoadSubCauseCode: IASN1PreparedElement {
            
            public static readonly HazardousLocation_ObstacleOnTheRoadSubCauseCode Unavailable = new(0);
            public static readonly HazardousLocation_ObstacleOnTheRoadSubCauseCode ShedLoad = new(1);
            public static readonly HazardousLocation_ObstacleOnTheRoadSubCauseCode PartsOfVehicles = new(2);
            public static readonly HazardousLocation_ObstacleOnTheRoadSubCauseCode PartsOfTyres = new(3);
            public static readonly HazardousLocation_ObstacleOnTheRoadSubCauseCode BigObjects = new(4);
            public static readonly HazardousLocation_ObstacleOnTheRoadSubCauseCode FallenTrees = new(5);
            public static readonly HazardousLocation_ObstacleOnTheRoadSubCauseCode HubCaps = new(6);
            public static readonly HazardousLocation_ObstacleOnTheRoadSubCauseCode WaitingVehicles = new(7);

            private int val;

            [ASN1Integer( Name = "HazardousLocation-ObstacleOnTheRoadSubCauseCode" )]
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 255L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public HazardousLocation_ObstacleOnTheRoadSubCauseCode() {
            }

            public HazardousLocation_ObstacleOnTheRoadSubCauseCode(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(HazardousLocation_ObstacleOnTheRoadSubCauseCode));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
