
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "Heading", IsExtensible = false, IsSet = false)]
    public class Heading : IASN1PreparedElement {
                
	private HeadingValue headingValue_ ;
	
        [ASN1Element ( Name = "headingValue", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public HeadingValue HeadingValue
        {
            get { return headingValue_; }
            set { headingValue_ = value;  }
        }
        
                
          
	private HeadingConfidence headingConfidence_ ;
	
        [ASN1Element ( Name = "headingConfidence", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public HeadingConfidence HeadingConfidence
        {
            get { return headingConfidence_; }
            set { headingConfidence_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Heading));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
