
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "HeadingConfidence" )]
    public class HeadingConfidence: IASN1PreparedElement {
            
            public static readonly HeadingConfidence EqualOrWithinZeroPointOneDegree = new(1);
            public static readonly HeadingConfidence EqualOrWithinOneDegree = new(10);
            public static readonly HeadingConfidence OutOfRange = new(126);
            public static readonly HeadingConfidence Unavailable = new(127);

            private int val;

            [ASN1Integer( Name = "HeadingConfidence" )]
            [ASN1ValueRangeConstraint ( Min = 1L, Max = 127L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public HeadingConfidence() {
            }

            public HeadingConfidence(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(HeadingConfidence));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
