
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "HeadingValue" )]
    public class HeadingValue: IASN1PreparedElement {
            
            public static readonly HeadingValue Wgs84North = new(0);
            public static readonly HeadingValue Wgs84East = new(900);
            public static readonly HeadingValue Wgs84South = new(1800);
            public static readonly HeadingValue Wgs84West = new(2700);
            public static readonly HeadingValue Unavailable = new(3601);

            private int val;

            [ASN1Integer( Name = "HeadingValue" )]
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 3601L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public HeadingValue() {
            }

            public HeadingValue(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(HeadingValue));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
