
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Choice ( Name = "HighFrequencyContainer", IsExtensible = true) ]
    public class HighFrequencyContainer : IASN1PreparedElement {
                    
        
	private BasicVehicleContainerHighFrequency basicVehicleContainerHighFrequency_ ;
        private bool  basicVehicleContainerHighFrequency_selected = false ;
        
                
        
        [ASN1Element ( Name = "basicVehicleContainerHighFrequency", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public BasicVehicleContainerHighFrequency BasicVehicleContainerHighFrequency
        {
            get { return basicVehicleContainerHighFrequency_; }
            set { selectBasicVehicleContainerHighFrequency(value); }
        }
        
                
          
        
	private RSUContainerHighFrequency rsuContainerHighFrequency_ ;
        private bool  rsuContainerHighFrequency_selected = false ;
        
                
        
        [ASN1Element ( Name = "rsuContainerHighFrequency", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public RSUContainerHighFrequency RsuContainerHighFrequency
        {
            get { return rsuContainerHighFrequency_; }
            set { selectRsuContainerHighFrequency(value); }
        }
        
                
          
        public bool isBasicVehicleContainerHighFrequencySelected () {
            return this.basicVehicleContainerHighFrequency_selected ;
        }

        


        public void selectBasicVehicleContainerHighFrequency (BasicVehicleContainerHighFrequency val) {
            this.basicVehicleContainerHighFrequency_ = val;
            this.basicVehicleContainerHighFrequency_selected = true;
            
            
                    this.rsuContainerHighFrequency_selected = false;
                            
        }
        
          
        public bool isRsuContainerHighFrequencySelected () {
            return this.rsuContainerHighFrequency_selected ;
        }

        


        public void selectRsuContainerHighFrequency (RSUContainerHighFrequency val) {
            this.rsuContainerHighFrequency_ = val;
            this.rsuContainerHighFrequency_selected = true;
            
            
                    this.basicVehicleContainerHighFrequency_selected = false;
                            
        }
        
  

            public void initWithDefaults()
	    {
	    }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(HighFrequencyContainer));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
