
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "ItsPduHeader", IsExtensible = false, IsSet = false)]
    public class ItsPduHeader : IASN1PreparedElement {
                
	private int protocolVersion_ ;
	[ASN1Integer( Name = "" )]
    [ASN1ValueRangeConstraint ( Min = 0L, Max = 255L, IsExtensible = false) ]
	    
        [ASN1Element ( Name = "protocolVersion", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public int ProtocolVersion
        {
            get { return protocolVersion_; }
            set { protocolVersion_ = value;  }
        }
        
                
          
	private int messageID_ ;
	[ASN1Integer( Name = "" )]
    [ASN1ValueRangeConstraint ( Min = 0L, Max = 255L, IsExtensible = false) ]
	    
        [ASN1Element ( Name = "messageID", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public int MessageID
        {
            get { return messageID_; }
            set { messageID_ = value;  }
        }
        
                
          
	private StationID stationID_ ;
	
        [ASN1Element ( Name = "stationID", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public StationID StationID
        {
            get { return stationID_; }
            set { stationID_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ItsPduHeader));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
