
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "LateralAccelerationValue" )]
    public class LateralAccelerationValue: IASN1PreparedElement {
            
            public static readonly LateralAccelerationValue PointOneMeterPerSecSquaredToRight = new(-1);
            public static readonly LateralAccelerationValue PointOneMeterPerSecSquaredToLeft = new(1);
            public static readonly LateralAccelerationValue Unavailable = new(161);

            private int val;

            [ASN1Integer( Name = "LateralAccelerationValue" )]
            [ASN1ValueRangeConstraint ( Min = -160L, Max = 161L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public LateralAccelerationValue() {
            }

            public LateralAccelerationValue(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(LateralAccelerationValue));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
