
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "LateralAcceleration", IsExtensible = false, IsSet = false)]
    public class LateralAcceleration : IASN1PreparedElement {
                
	private LateralAccelerationValue lateralAccelerationValue_ ;
	
        [ASN1Element ( Name = "lateralAccelerationValue", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public LateralAccelerationValue LateralAccelerationValue
        {
            get { return lateralAccelerationValue_; }
            set { lateralAccelerationValue_ = value;  }
        }
        
                
          
	private AccelerationConfidence lateralAccelerationConfidence_ ;
	
        [ASN1Element ( Name = "lateralAccelerationConfidence", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public AccelerationConfidence LateralAccelerationConfidence
        {
            get { return lateralAccelerationConfidence_; }
            set { lateralAccelerationConfidence_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(LateralAcceleration));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
