
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "Latitude" )]
    public class Latitude: IASN1PreparedElement {
            
            public static readonly Latitude OneMicrodegreeNorth = new(10);
            public static readonly Latitude OneMicrodegreeSouth = new(-10);
            public static readonly Latitude Unavailable = new(900000001);

            private int val;

            [ASN1Integer( Name = "Latitude" )]
            [ASN1ValueRangeConstraint ( Min = -900000000L, Max = 900000001L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public Latitude() {
            }

            public Latitude(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Latitude));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
