
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "LongitudinalAcceleration", IsExtensible = false, IsSet = false)]
    public class LongitudinalAcceleration : IASN1PreparedElement {
                
	private LongitudinalAccelerationValue longitudinalAccelerationValue_ ;
	
        [ASN1Element ( Name = "longitudinalAccelerationValue", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public LongitudinalAccelerationValue LongitudinalAccelerationValue
        {
            get { return longitudinalAccelerationValue_; }
            set { longitudinalAccelerationValue_ = value;  }
        }
        
                
          
	private AccelerationConfidence longitudinalAccelerationConfidence_ ;
	
        [ASN1Element ( Name = "longitudinalAccelerationConfidence", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public AccelerationConfidence LongitudinalAccelerationConfidence
        {
            get { return longitudinalAccelerationConfidence_; }
            set { longitudinalAccelerationConfidence_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(LongitudinalAcceleration));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
