
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Choice ( Name = "LowFrequencyContainer", IsExtensible = true) ]
    public class LowFrequencyContainer : IASN1PreparedElement {
                    
        
	private BasicVehicleContainerLowFrequency basicVehicleContainerLowFrequency_ ;
        private bool  basicVehicleContainerLowFrequency_selected = false ;
        
                
        
        [ASN1Element ( Name = "basicVehicleContainerLowFrequency", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public BasicVehicleContainerLowFrequency BasicVehicleContainerLowFrequency
        {
            get { return basicVehicleContainerLowFrequency_; }
            set { selectBasicVehicleContainerLowFrequency(value); }
        }
        
                
          
        public bool isBasicVehicleContainerLowFrequencySelected () {
            return this.basicVehicleContainerLowFrequency_selected ;
        }

        


        public void selectBasicVehicleContainerLowFrequency (BasicVehicleContainerLowFrequency val) {
            this.basicVehicleContainerLowFrequency_ = val;
            this.basicVehicleContainerLowFrequency_selected = true;
            
                        
        }
        
  

            public void initWithDefaults()
	    {
	    }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(LowFrequencyContainer));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
