
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "PathHistory" ) ]
    public class PathHistory : IASN1PreparedElement {

	    private System.Collections.Generic.ICollection<PathPoint> val = null; 
            
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 40L, IsExtensible = false) ]
	    
            [ASN1SequenceOf( Name = "PathHistory", IsSetOf = false) ]

            public System.Collections.Generic.ICollection<PathPoint> Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public void initValue() {
                this.Value = new System.Collections.Generic.List<PathPoint>();
            }
            
            public void Add(PathPoint item) {
                this.Value.Add(item);
            }

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(PathHistory));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
