
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "PathPoint", IsExtensible = false, IsSet = false)]
    public class PathPoint : IASN1PreparedElement {
                
	private DeltaReferencePosition pathPosition_ ;
	
        [ASN1Element ( Name = "pathPosition", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public DeltaReferencePosition PathPosition
        {
            get { return pathPosition_; }
            set { pathPosition_ = value;  }
        }
        
                
          
	private PathDeltaTime pathDeltaTime_ ;
	
        private bool  pathDeltaTime_present = false ;
	
        [ASN1Element ( Name = "pathDeltaTime", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public PathDeltaTime PathDeltaTime
        {
            get { return pathDeltaTime_; }
            set { pathDeltaTime_ = value; pathDeltaTime_present = true;  }
        }
        
                
  
        public bool isPathDeltaTimePresent () {
            return this.pathDeltaTime_present == true;
        }
        

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(PathPoint));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
