
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "PosConfidenceEllipse", IsExtensible = false, IsSet = false)]
    public class PosConfidenceEllipse : IASN1PreparedElement {
                
	private SemiAxisLength semiMajorConfidence_ ;
	
        [ASN1Element ( Name = "semiMajorConfidence", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public SemiAxisLength SemiMajorConfidence
        {
            get { return semiMajorConfidence_; }
            set { semiMajorConfidence_ = value;  }
        }
        
                
          
	private SemiAxisLength semiMinorConfidence_ ;
	
        [ASN1Element ( Name = "semiMinorConfidence", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public SemiAxisLength SemiMinorConfidence
        {
            get { return semiMinorConfidence_; }
            set { semiMinorConfidence_ = value;  }
        }
        
                
          
	private HeadingValue semiMajorOrientation_ ;
	
        [ASN1Element ( Name = "semiMajorOrientation", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public HeadingValue SemiMajorOrientation
        {
            get { return semiMajorOrientation_; }
            set { semiMajorOrientation_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(PosConfidenceEllipse));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
