
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "PosCentMass" )]
    public class PosCentMass: IASN1PreparedElement {
    
            private int val;
            
            [ASN1Integer( Name = "PosCentMass" )]
            [ASN1ValueRangeConstraint ( Min = 1L, Max = 63L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public PosCentMass() {
            }

            public PosCentMass(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(PosCentMass));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
