
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "PositioningSolutionType", IsExtensible = true, NumRootElements = 6)]
    public class PositioningSolutionType : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "noPositioningSolution", HasTag = true , Tag = 0 )]
            NoPositioningSolution , 
            [ASN1EnumItem ( Name = "sGNSS", HasTag = true , Tag = 1 )]
            SGNSS , 
            [ASN1EnumItem ( Name = "dGNSS", HasTag = true , Tag = 2 )]
            DGNSS , 
            [ASN1EnumItem ( Name = "sGNSSplusDR", HasTag = true , Tag = 3 )]
            SGNSSplusDR , 
            [ASN1EnumItem ( Name = "dGNSSplusDR", HasTag = true , Tag = 4 )]
            DGNSSplusDR , 
            [ASN1EnumItem ( Name = "dR", HasTag = true , Tag = 5 )]
            DR , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(PositioningSolutionType));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }


    }
            
}
