
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "PositionOfPillars" ) ]
    public class PositionOfPillars : IASN1PreparedElement {

	    private System.Collections.Generic.ICollection<PosPillar> val = null; 
            
            [ASN1ValueRangeConstraint ( Min = 1L, Max = 3L, IsExtensible = true) ]
	    
            [ASN1SequenceOf( Name = "PositionOfPillars", IsSetOf = false) ]

            public System.Collections.Generic.ICollection<PosPillar> Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public void initValue() {
                this.Value = new System.Collections.Generic.List<PosPillar>();
            }
            
            public void Add(PosPillar item) {
                this.Value.Add(item);
            }

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(PositionOfPillars));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
