
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "PositionOfOccupants") ]
    public class PositionOfOccupants : IASN1PreparedElement {
    
            private BitString val = null;

            [ASN1BitString( Name = "PositionOfOccupants") ]            
            
            [ASN1SizeConstraint ( Max = 20L )]
        
            public BitString Value
            {
                get { return val; }
                set { val = value; }
            }            
            
            public PositionOfOccupants() {
            }

            public PositionOfOccupants(BitString value) {
                this.Value = value;
            }            


            public void initWithDefaults()
	    {
	    }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(PositionOfOccupants));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
