
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "PosLonCarr" )]
    public class PosLonCarr: IASN1PreparedElement {
            
            public static readonly PosLonCarr OneCentimeter = new(1);
            public static readonly PosLonCarr Unavailable = new(127);

            private int val;

            [ASN1Integer( Name = "PosLonCarr" )]
            [ASN1ValueRangeConstraint ( Min = 1L, Max = 127L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public PosLonCarr() {
            }

            public PosLonCarr(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(PosLonCarr));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
