
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "ProtectedZoneType", IsExtensible = true, NumRootElements = 1)]
    public class ProtectedZoneType : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "cenDsrcTolling", HasTag = true , Tag = 0 )]
            CenDsrcTolling , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ProtectedZoneType));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }


    }
            
}
