
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "ProtectedCommunicationZone", IsExtensible = false, IsSet = false)]
    public class ProtectedCommunicationZone : IASN1PreparedElement {
                
	private ProtectedZoneType protectedZoneType_ ;
	
        [ASN1Element ( Name = "protectedZoneType", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public ProtectedZoneType ProtectedZoneType
        {
            get { return protectedZoneType_; }
            set { protectedZoneType_ = value;  }
        }
        
                
          
	private TimestampIts expiryTime_ ;
	
        private bool  expiryTime_present = false ;
	
        [ASN1Element ( Name = "expiryTime", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public TimestampIts ExpiryTime
        {
            get { return expiryTime_; }
            set { expiryTime_ = value; expiryTime_present = true;  }
        }
        
                
          
	private Latitude protectedZoneLatitude_ ;
	
        [ASN1Element ( Name = "protectedZoneLatitude", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public Latitude ProtectedZoneLatitude
        {
            get { return protectedZoneLatitude_; }
            set { protectedZoneLatitude_ = value;  }
        }
        
                
          
	private Longitude protectedZoneLongitude_ ;
	
        [ASN1Element ( Name = "protectedZoneLongitude", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public Longitude ProtectedZoneLongitude
        {
            get { return protectedZoneLongitude_; }
            set { protectedZoneLongitude_ = value;  }
        }
        
                
          
	private ProtectedZoneRadius protectedZoneRadius_ ;
	
        private bool  protectedZoneRadius_present = false ;
	
        [ASN1Element ( Name = "protectedZoneRadius", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public ProtectedZoneRadius ProtectedZoneRadius
        {
            get { return protectedZoneRadius_; }
            set { protectedZoneRadius_ = value; protectedZoneRadius_present = true;  }
        }
        
                
          
	private ProtectedZoneID protectedZoneID_ ;
	
        private bool  protectedZoneID_present = false ;
	
        [ASN1Element ( Name = "protectedZoneID", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public ProtectedZoneID ProtectedZoneID
        {
            get { return protectedZoneID_; }
            set { protectedZoneID_ = value; protectedZoneID_present = true;  }
        }
        
                
  
        public bool isExpiryTimePresent () {
            return this.expiryTime_present == true;
        }
        
        public bool isProtectedZoneRadiusPresent () {
            return this.protectedZoneRadius_present == true;
        }
        
        public bool isProtectedZoneIDPresent () {
            return this.protectedZoneID_present == true;
        }
        

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ProtectedCommunicationZone));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
