
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "ProtectedZoneRadius" )]
    public class ProtectedZoneRadius: IASN1PreparedElement {
            
            public static readonly ProtectedZoneRadius OneMeter = new(1);

            private int val;

            [ASN1Integer( Name = "ProtectedZoneRadius" )]
            [ASN1ValueRangeConstraint ( Min = 1L, Max = 255L, IsExtensible = true) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public ProtectedZoneRadius() {
            }

            public ProtectedZoneRadius(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ProtectedZoneRadius));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
