
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "PublicTransportContainer", IsExtensible = false, IsSet = false)]
    public class PublicTransportContainer : IASN1PreparedElement {
                
	private EmbarkationStatus embarkationStatus_ ;
	
        [ASN1Element ( Name = "embarkationStatus", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public EmbarkationStatus EmbarkationStatus
        {
            get { return embarkationStatus_; }
            set { embarkationStatus_ = value;  }
        }
        
                
          
	private PtActivation ptActivation_ ;
	
        private bool  ptActivation_present = false ;
	
        [ASN1Element ( Name = "ptActivation", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public PtActivation PtActivation
        {
            get { return ptActivation_; }
            set { ptActivation_ = value; ptActivation_present = true;  }
        }
        
                
  
        public bool isPtActivationPresent () {
            return this.ptActivation_present == true;
        }
        

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(PublicTransportContainer));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
