
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "ReferencePosition", IsExtensible = false, IsSet = false)]
    public class ReferencePosition : IASN1PreparedElement {
                
	private Latitude latitude_ ;
	
        [ASN1Element ( Name = "latitude", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public Latitude Latitude
        {
            get { return latitude_; }
            set { latitude_ = value;  }
        }
        
                
          
	private Longitude longitude_ ;
	
        [ASN1Element ( Name = "longitude", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public Longitude Longitude
        {
            get { return longitude_; }
            set { longitude_ = value;  }
        }
        
                
          
	private PosConfidenceEllipse positionConfidenceEllipse_ ;
	
        [ASN1Element ( Name = "positionConfidenceEllipse", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public PosConfidenceEllipse PositionConfidenceEllipse
        {
            get { return positionConfidenceEllipse_; }
            set { positionConfidenceEllipse_ = value;  }
        }
        
                
          
	private Altitude altitude_ ;
	
        [ASN1Element ( Name = "altitude", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public Altitude Altitude
        {
            get { return altitude_; }
            set { altitude_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ReferencePosition));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
