
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "RelevanceTrafficDirection", IsExtensible = false, NumRootElements = 4)]
    public class RelevanceTrafficDirection : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "allTrafficDirections", HasTag = true , Tag = 0 )]
            AllTrafficDirections , 
            [ASN1EnumItem ( Name = "upstreamTraffic", HasTag = true , Tag = 1 )]
            UpstreamTraffic , 
            [ASN1EnumItem ( Name = "downstreamTraffic", HasTag = true , Tag = 2 )]
            DownstreamTraffic , 
            [ASN1EnumItem ( Name = "oppositeTraffic", HasTag = true , Tag = 3 )]
            OppositeTraffic , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(RelevanceTrafficDirection));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }


    }
            
}
