
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "RelevanceDistance", IsExtensible = false, NumRootElements = 8)]
    public class RelevanceDistance : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "lessThan50m", HasTag = true , Tag = 0 )]
            lessThan50m , 
            [ASN1EnumItem ( Name = "lessThan100m", HasTag = true , Tag = 1 )]
            lessThan100m , 
            [ASN1EnumItem ( Name = "lessThan200m", HasTag = true , Tag = 2 )]
            lessThan200m , 
            [ASN1EnumItem ( Name = "lessThan500m", HasTag = true , Tag = 3 )]
            lessThan500m , 
            [ASN1EnumItem ( Name = "lessThan1000m", HasTag = true , Tag = 4 )]
            lessThan1000m , 
            [ASN1EnumItem ( Name = "lessThan5km", HasTag = true , Tag = 5 )]
            lessThan5km , 
            [ASN1EnumItem ( Name = "lessThan10km", HasTag = true , Tag = 6 )]
            lessThan10km , 
            [ASN1EnumItem ( Name = "over10km", HasTag = true , Tag = 7 )]
            over10km , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(RelevanceDistance));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }


    }
            
}
