
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "RoadWorksContainerBasic", IsExtensible = false, IsSet = false)]
    public class RoadWorksContainerBasic : IASN1PreparedElement {
                
	private RoadworksSubCauseCode roadworksSubCauseCode_ ;
	
        private bool  roadworksSubCauseCode_present = false ;
	
        [ASN1Element ( Name = "roadworksSubCauseCode", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public RoadworksSubCauseCode RoadworksSubCauseCode
        {
            get { return roadworksSubCauseCode_; }
            set { roadworksSubCauseCode_ = value; roadworksSubCauseCode_present = true;  }
        }
        
                
          
	private LightBarSirenInUse lightBarSirenInUse_ ;
	
        [ASN1Element ( Name = "lightBarSirenInUse", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public LightBarSirenInUse LightBarSirenInUse
        {
            get { return lightBarSirenInUse_; }
            set { lightBarSirenInUse_ = value;  }
        }
        
                
          
	private ClosedLanes closedLanes_ ;
	
        private bool  closedLanes_present = false ;
	
        [ASN1Element ( Name = "closedLanes", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public ClosedLanes ClosedLanes
        {
            get { return closedLanes_; }
            set { closedLanes_ = value; closedLanes_present = true;  }
        }
        
                
  
        public bool isRoadworksSubCauseCodePresent () {
            return this.roadworksSubCauseCode_present == true;
        }
        
        public bool isClosedLanesPresent () {
            return this.closedLanes_present == true;
        }
        

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(RoadWorksContainerBasic));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
