
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "RoadworksSubCauseCode" )]
    public class RoadworksSubCauseCode: IASN1PreparedElement {
            
            public static readonly RoadworksSubCauseCode Unavailable = new(0);
            public static readonly RoadworksSubCauseCode MajorRoadworks = new(1);
            public static readonly RoadworksSubCauseCode RoadMarkingWork = new(2);
            public static readonly RoadworksSubCauseCode SlowMovingRoadMaintenance = new(3);
            public static readonly RoadworksSubCauseCode ShortTermStationaryRoadworks = new(4);
            public static readonly RoadworksSubCauseCode StreetCleaning = new(5);
            public static readonly RoadworksSubCauseCode WinterService = new(6);

            private int val;

            [ASN1Integer( Name = "RoadworksSubCauseCode" )]
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 255L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public RoadworksSubCauseCode() {
            }

            public RoadworksSubCauseCode(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(RoadworksSubCauseCode));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
