
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "RoadType", IsExtensible = false, NumRootElements = 4)]
    public class RoadType : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "urban-NoStructuralSeparationToOppositeLanes", HasTag = true , Tag = 0 )]
            Urban_NoStructuralSeparationToOppositeLanes , 
            [ASN1EnumItem ( Name = "urban-WithStructuralSeparationToOppositeLanes", HasTag = true , Tag = 1 )]
            Urban_WithStructuralSeparationToOppositeLanes , 
            [ASN1EnumItem ( Name = "nonUrban-NoStructuralSeparationToOppositeLanes", HasTag = true , Tag = 2 )]
            NonUrban_NoStructuralSeparationToOppositeLanes , 
            [ASN1EnumItem ( Name = "nonUrban-WithStructuralSeparationToOppositeLanes", HasTag = true , Tag = 3 )]
            NonUrban_WithStructuralSeparationToOppositeLanes , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(RoadType));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }


    }
            
}
