
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "RSUContainerHighFrequency", IsExtensible = true, IsSet = false)]
    public class RSUContainerHighFrequency : IASN1PreparedElement {
                
	private ProtectedCommunicationZonesRSU protectedCommunicationZonesRSU_ ;
	
        private bool  protectedCommunicationZonesRSU_present = false ;
	
        [ASN1Element ( Name = "protectedCommunicationZonesRSU", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public ProtectedCommunicationZonesRSU ProtectedCommunicationZonesRSU
        {
            get { return protectedCommunicationZonesRSU_; }
            set { protectedCommunicationZonesRSU_ = value; protectedCommunicationZonesRSU_present = true;  }
        }
        
                
  
        public bool isProtectedCommunicationZonesRSUPresent () {
            return this.protectedCommunicationZonesRSU_present == true;
        }
        

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(RSUContainerHighFrequency));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
