
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "SafetyCarContainer", IsExtensible = false, IsSet = false)]
    public class SafetyCarContainer : IASN1PreparedElement {
                
	private LightBarSirenInUse lightBarSirenInUse_ ;
	
        [ASN1Element ( Name = "lightBarSirenInUse", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public LightBarSirenInUse LightBarSirenInUse
        {
            get { return lightBarSirenInUse_; }
            set { lightBarSirenInUse_ = value;  }
        }
        
                
          
	private CauseCode incidentIndication_ ;
	
        private bool  incidentIndication_present = false ;
	
        [ASN1Element ( Name = "incidentIndication", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public CauseCode IncidentIndication
        {
            get { return incidentIndication_; }
            set { incidentIndication_ = value; incidentIndication_present = true;  }
        }
        
                
          
	private TrafficRule trafficRule_ ;
	
        private bool  trafficRule_present = false ;
	
        [ASN1Element ( Name = "trafficRule", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public TrafficRule TrafficRule
        {
            get { return trafficRule_; }
            set { trafficRule_ = value; trafficRule_present = true;  }
        }
        
                
          
	private SpeedLimit speedLimit_ ;
	
        private bool  speedLimit_present = false ;
	
        [ASN1Element ( Name = "speedLimit", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public SpeedLimit SpeedLimit
        {
            get { return speedLimit_; }
            set { speedLimit_ = value; speedLimit_present = true;  }
        }
        
                
  
        public bool isIncidentIndicationPresent () {
            return this.incidentIndication_present == true;
        }
        
        public bool isTrafficRulePresent () {
            return this.trafficRule_present == true;
        }
        
        public bool isSpeedLimitPresent () {
            return this.speedLimit_present == true;
        }
        

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(SafetyCarContainer));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
