
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "SlowVehicleSubCauseCode" )]
    public class SlowVehicleSubCauseCode: IASN1PreparedElement {
            
            public static readonly SlowVehicleSubCauseCode Unavailable = new(0);
            public static readonly SlowVehicleSubCauseCode MaintenanceVehicle = new(1);
            public static readonly SlowVehicleSubCauseCode VehiclesSlowingToLookAtAccident = new(2);
            public static readonly SlowVehicleSubCauseCode AbnormalLoad = new(3);
            public static readonly SlowVehicleSubCauseCode AbnormalWideLoad = new(4);
            public static readonly SlowVehicleSubCauseCode Convoy = new(5);
            public static readonly SlowVehicleSubCauseCode Snowplough = new(6);
            public static readonly SlowVehicleSubCauseCode Deicing = new(7);
            public static readonly SlowVehicleSubCauseCode SaltingVehicles = new(8);

            private int val;

            [ASN1Integer( Name = "SlowVehicleSubCauseCode" )]
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 255L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public SlowVehicleSubCauseCode() {
            }

            public SlowVehicleSubCauseCode(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(SlowVehicleSubCauseCode));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
