
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "SpecialTransportContainer", IsExtensible = false, IsSet = false)]
    public class SpecialTransportContainer : IASN1PreparedElement {
                
	private SpecialTransportType specialTransportType_ ;
	
        [ASN1Element ( Name = "specialTransportType", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public SpecialTransportType SpecialTransportType
        {
            get { return specialTransportType_; }
            set { specialTransportType_ = value;  }
        }
        
                
          
	private LightBarSirenInUse lightBarSirenInUse_ ;
	
        [ASN1Element ( Name = "lightBarSirenInUse", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public LightBarSirenInUse LightBarSirenInUse
        {
            get { return lightBarSirenInUse_; }
            set { lightBarSirenInUse_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(SpecialTransportContainer));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
