
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Choice ( Name = "SpecialVehicleContainer", IsExtensible = true) ]
    public class SpecialVehicleContainer : IASN1PreparedElement {
                    
        
	private PublicTransportContainer publicTransportContainer_ ;
        private bool  publicTransportContainer_selected = false ;
        
                
        
        [ASN1Element ( Name = "publicTransportContainer", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public PublicTransportContainer PublicTransportContainer
        {
            get { return publicTransportContainer_; }
            set { selectPublicTransportContainer(value); }
        }
        
                
          
        
	private SpecialTransportContainer specialTransportContainer_ ;
        private bool  specialTransportContainer_selected = false ;
        
                
        
        [ASN1Element ( Name = "specialTransportContainer", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public SpecialTransportContainer SpecialTransportContainer
        {
            get { return specialTransportContainer_; }
            set { selectSpecialTransportContainer(value); }
        }
        
                
          
        
	private DangerousGoodsContainer dangerousGoodsContainer_ ;
        private bool  dangerousGoodsContainer_selected = false ;
        
                
        
        [ASN1Element ( Name = "dangerousGoodsContainer", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public DangerousGoodsContainer DangerousGoodsContainer
        {
            get { return dangerousGoodsContainer_; }
            set { selectDangerousGoodsContainer(value); }
        }
        
                
          
        
	private RoadWorksContainerBasic roadWorksContainerBasic_ ;
        private bool  roadWorksContainerBasic_selected = false ;
        
                
        
        [ASN1Element ( Name = "roadWorksContainerBasic", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public RoadWorksContainerBasic RoadWorksContainerBasic
        {
            get { return roadWorksContainerBasic_; }
            set { selectRoadWorksContainerBasic(value); }
        }
        
                
          
        
	private RescueContainer rescueContainer_ ;
        private bool  rescueContainer_selected = false ;
        
                
        
        [ASN1Element ( Name = "rescueContainer", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public RescueContainer RescueContainer
        {
            get { return rescueContainer_; }
            set { selectRescueContainer(value); }
        }
        
                
          
        
	private EmergencyContainer emergencyContainer_ ;
        private bool  emergencyContainer_selected = false ;
        
                
        
        [ASN1Element ( Name = "emergencyContainer", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public EmergencyContainer EmergencyContainer
        {
            get { return emergencyContainer_; }
            set { selectEmergencyContainer(value); }
        }
        
                
          
        
	private SafetyCarContainer safetyCarContainer_ ;
        private bool  safetyCarContainer_selected = false ;
        
                
        
        [ASN1Element ( Name = "safetyCarContainer", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public SafetyCarContainer SafetyCarContainer
        {
            get { return safetyCarContainer_; }
            set { selectSafetyCarContainer(value); }
        }
        
                
          
        public bool isPublicTransportContainerSelected () {
            return this.publicTransportContainer_selected ;
        }

        


        public void selectPublicTransportContainer (PublicTransportContainer val) {
            this.publicTransportContainer_ = val;
            this.publicTransportContainer_selected = true;
            
            
                    this.specialTransportContainer_selected = false;
                
                    this.dangerousGoodsContainer_selected = false;
                
                    this.roadWorksContainerBasic_selected = false;
                
                    this.rescueContainer_selected = false;
                
                    this.emergencyContainer_selected = false;
                
                    this.safetyCarContainer_selected = false;
                            
        }
        
          
        public bool isSpecialTransportContainerSelected () {
            return this.specialTransportContainer_selected ;
        }

        


        public void selectSpecialTransportContainer (SpecialTransportContainer val) {
            this.specialTransportContainer_ = val;
            this.specialTransportContainer_selected = true;
            
            
                    this.publicTransportContainer_selected = false;
                
                    this.dangerousGoodsContainer_selected = false;
                
                    this.roadWorksContainerBasic_selected = false;
                
                    this.rescueContainer_selected = false;
                
                    this.emergencyContainer_selected = false;
                
                    this.safetyCarContainer_selected = false;
                            
        }
        
          
        public bool isDangerousGoodsContainerSelected () {
            return this.dangerousGoodsContainer_selected ;
        }

        


        public void selectDangerousGoodsContainer (DangerousGoodsContainer val) {
            this.dangerousGoodsContainer_ = val;
            this.dangerousGoodsContainer_selected = true;
            
            
                    this.publicTransportContainer_selected = false;
                
                    this.specialTransportContainer_selected = false;
                
                    this.roadWorksContainerBasic_selected = false;
                
                    this.rescueContainer_selected = false;
                
                    this.emergencyContainer_selected = false;
                
                    this.safetyCarContainer_selected = false;
                            
        }
        
          
        public bool isRoadWorksContainerBasicSelected () {
            return this.roadWorksContainerBasic_selected ;
        }

        


        public void selectRoadWorksContainerBasic (RoadWorksContainerBasic val) {
            this.roadWorksContainerBasic_ = val;
            this.roadWorksContainerBasic_selected = true;
            
            
                    this.publicTransportContainer_selected = false;
                
                    this.specialTransportContainer_selected = false;
                
                    this.dangerousGoodsContainer_selected = false;
                
                    this.rescueContainer_selected = false;
                
                    this.emergencyContainer_selected = false;
                
                    this.safetyCarContainer_selected = false;
                            
        }
        
          
        public bool isRescueContainerSelected () {
            return this.rescueContainer_selected ;
        }

        


        public void selectRescueContainer (RescueContainer val) {
            this.rescueContainer_ = val;
            this.rescueContainer_selected = true;
            
            
                    this.publicTransportContainer_selected = false;
                
                    this.specialTransportContainer_selected = false;
                
                    this.dangerousGoodsContainer_selected = false;
                
                    this.roadWorksContainerBasic_selected = false;
                
                    this.emergencyContainer_selected = false;
                
                    this.safetyCarContainer_selected = false;
                            
        }
        
          
        public bool isEmergencyContainerSelected () {
            return this.emergencyContainer_selected ;
        }

        


        public void selectEmergencyContainer (EmergencyContainer val) {
            this.emergencyContainer_ = val;
            this.emergencyContainer_selected = true;
            
            
                    this.publicTransportContainer_selected = false;
                
                    this.specialTransportContainer_selected = false;
                
                    this.dangerousGoodsContainer_selected = false;
                
                    this.roadWorksContainerBasic_selected = false;
                
                    this.rescueContainer_selected = false;
                
                    this.safetyCarContainer_selected = false;
                            
        }
        
          
        public bool isSafetyCarContainerSelected () {
            return this.safetyCarContainer_selected ;
        }

        


        public void selectSafetyCarContainer (SafetyCarContainer val) {
            this.safetyCarContainer_ = val;
            this.safetyCarContainer_selected = true;
            
            
                    this.publicTransportContainer_selected = false;
                
                    this.specialTransportContainer_selected = false;
                
                    this.dangerousGoodsContainer_selected = false;
                
                    this.roadWorksContainerBasic_selected = false;
                
                    this.rescueContainer_selected = false;
                
                    this.emergencyContainer_selected = false;
                            
        }
        
  

            public void initWithDefaults()
	    {
	    }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(SpecialVehicleContainer));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
