
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "Speed", IsExtensible = false, IsSet = false)]
    public class Speed : IASN1PreparedElement {
                
	private SpeedValue speedValue_ ;
	
        [ASN1Element ( Name = "speedValue", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public SpeedValue SpeedValue
        {
            get { return speedValue_; }
            set { speedValue_ = value;  }
        }
        
                
          
	private SpeedConfidence speedConfidence_ ;
	
        [ASN1Element ( Name = "speedConfidence", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public SpeedConfidence SpeedConfidence
        {
            get { return speedConfidence_; }
            set { speedConfidence_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Speed));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
