
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "StationarySince", IsExtensible = false, NumRootElements = 4)]
    public class StationarySince : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "lessThan1Minute", HasTag = true , Tag = 0 )]
            lessThan1Minute , 
            [ASN1EnumItem ( Name = "lessThan2Minutes", HasTag = true , Tag = 1 )]
            lessThan2Minutes , 
            [ASN1EnumItem ( Name = "lessThan15Minutes", HasTag = true , Tag = 2 )]
            lessThan15Minutes , 
            [ASN1EnumItem ( Name = "equalOrGreater15Minutes", HasTag = true , Tag = 3 )]
            equalOrGreater15Minutes , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(StationarySince));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }


    }
            
}
