
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "StationType" )]
    public class StationType: IASN1PreparedElement {
            
            public static readonly StationType Unknown = new(0);
            public static readonly StationType Pedestrian = new(1);
            public static readonly StationType Cyclist = new(2);
            public static readonly StationType Moped = new(3);
            public static readonly StationType Motorcycle = new(4);
            public static readonly StationType PassengerCar = new(5);
            public static readonly StationType Bus = new(6);
            public static readonly StationType LightTruck = new(7);
            public static readonly StationType HeavyTruck = new(8);
            public static readonly StationType Trailer = new(9);
            public static readonly StationType SpecialVehicles = new(10);
            public static readonly StationType Tram = new(11);
            public static readonly StationType RoadSideUnit = new(15);

            private int val;

            [ASN1Integer( Name = "StationType" )]
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 255L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public StationType() {
            }

            public StationType(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(StationType));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
