
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "SteeringWheelAngle", IsExtensible = false, IsSet = false)]
    public class SteeringWheelAngle : IASN1PreparedElement {
                
	private SteeringWheelAngleValue steeringWheelAngleValue_ ;
	
        [ASN1Element ( Name = "steeringWheelAngleValue", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public SteeringWheelAngleValue SteeringWheelAngleValue
        {
            get { return steeringWheelAngleValue_; }
            set { steeringWheelAngleValue_ = value;  }
        }
        
                
          
	private SteeringWheelAngleConfidence steeringWheelAngleConfidence_ ;
	
        [ASN1Element ( Name = "steeringWheelAngleConfidence", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public SteeringWheelAngleConfidence SteeringWheelAngleConfidence
        {
            get { return steeringWheelAngleConfidence_; }
            set { steeringWheelAngleConfidence_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(SteeringWheelAngle));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
