
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "SteeringWheelAngleValue" )]
    public class SteeringWheelAngleValue: IASN1PreparedElement {
            
            public static readonly SteeringWheelAngleValue Straight = new(0);
            public static readonly SteeringWheelAngleValue OnePointFiveDegreesToRight = new(-1);
            public static readonly SteeringWheelAngleValue OnePointFiveDegreesToLeft = new(1);
            public static readonly SteeringWheelAngleValue Unavailable = new(512);

            private int val;

            [ASN1Integer( Name = "SteeringWheelAngleValue" )]
            [ASN1ValueRangeConstraint ( Min = -511L, Max = 512L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public SteeringWheelAngleValue() {
            }

            public SteeringWheelAngleValue(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(SteeringWheelAngleValue));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
