
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "TimestampIts" )]
    public class TimestampIts: IASN1PreparedElement {
            
            public static readonly TimestampIts UtcStartOf2004 = new(0);
            public static readonly TimestampIts OneMillisecAfterUTCStartOf2004 = new(1);

            private long val;

            [ASN1Integer( Name = "TimestampIts" )]
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 4398046511103L, IsExtensible = false) ]
	    
            public long Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public TimestampIts() {
            }

            public TimestampIts(long value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(TimestampIts));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
