
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "TrafficRule", IsExtensible = true, NumRootElements = 4)]
    public class TrafficRule : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "noPassing", HasTag = true , Tag = 0 )]
            NoPassing , 
            [ASN1EnumItem ( Name = "noPassingForTrucks", HasTag = true , Tag = 1 )]
            NoPassingForTrucks , 
            [ASN1EnumItem ( Name = "passToRight", HasTag = true , Tag = 2 )]
            PassToRight , 
            [ASN1EnumItem ( Name = "passToLeft", HasTag = true , Tag = 3 )]
            PassToLeft , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(TrafficRule));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }


    }
            
}
