
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "TrafficConditionSubCauseCode" )]
    public class TrafficConditionSubCauseCode: IASN1PreparedElement {
            
            public static readonly TrafficConditionSubCauseCode Unavailable = new(0);
            public static readonly TrafficConditionSubCauseCode IncreasedVolumeOfTraffic = new(1);
            public static readonly TrafficConditionSubCauseCode TrafficJamSlowlyIncreasing = new(2);
            public static readonly TrafficConditionSubCauseCode TrafficJamIncreasing = new(3);
            public static readonly TrafficConditionSubCauseCode TrafficJamStronglyIncreasing = new(4);
            public static readonly TrafficConditionSubCauseCode TrafficStationary = new(5);
            public static readonly TrafficConditionSubCauseCode TrafficJamSlightlyDecreasing = new(6);
            public static readonly TrafficConditionSubCauseCode TrafficJamDecreasing = new(7);
            public static readonly TrafficConditionSubCauseCode TrafficJamStronglyDecreasing = new(8);

            private int val;

            [ASN1Integer( Name = "TrafficConditionSubCauseCode" )]
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 255L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public TrafficConditionSubCauseCode() {
            }

            public TrafficConditionSubCauseCode(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(TrafficConditionSubCauseCode));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
