
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "VDS") ]
    public class VDS: IASN1PreparedElement {

            private String val;
    
            [ASN1String( Name = "VDS", 
        StringType =  UniversalTags.IA5String , IsUCS = false) ]
            
            [ASN1SizeConstraint ( Max = 6L )]
        
            public String Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public VDS() {
            }

            public VDS(String val) {
                this.val = val;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(VDS));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
