
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "VehicleBreakdownSubCauseCode" )]
    public class VehicleBreakdownSubCauseCode: IASN1PreparedElement {
            
            public static readonly VehicleBreakdownSubCauseCode Unavailable = new(0);
            public static readonly VehicleBreakdownSubCauseCode LackOfFuel = new(1);
            public static readonly VehicleBreakdownSubCauseCode LackOfBatteryPower = new(2);
            public static readonly VehicleBreakdownSubCauseCode EngineProblem = new(3);
            public static readonly VehicleBreakdownSubCauseCode TransmissionProblem = new(4);
            public static readonly VehicleBreakdownSubCauseCode EngineCoolingProblem = new(5);
            public static readonly VehicleBreakdownSubCauseCode BrakingSystemProblem = new(6);
            public static readonly VehicleBreakdownSubCauseCode SteeringProblem = new(7);
            public static readonly VehicleBreakdownSubCauseCode TyrePuncture = new(8);

            private int val;

            [ASN1Integer( Name = "VehicleBreakdownSubCauseCode" )]
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 255L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public VehicleBreakdownSubCauseCode() {
            }

            public VehicleBreakdownSubCauseCode(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(VehicleBreakdownSubCauseCode));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
