
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "VehicleLengthConfidenceIndication", IsExtensible = false, NumRootElements = 5)]
    public class VehicleLengthConfidenceIndication : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "noTrailerPresent", HasTag = true , Tag = 0 )]
            noTrailerPresent , 
            [ASN1EnumItem ( Name = "trailerPresentWithKnownLength", HasTag = true , Tag = 1 )]
            trailerPresentWithKnownLength , 
            [ASN1EnumItem ( Name = "trailerPresentWithUnknownLength", HasTag = true , Tag = 2 )]
            trailerPresentWithUnknownLength , 
            [ASN1EnumItem ( Name = "trailerPresenceIsUnknown", HasTag = true , Tag = 3 )]
            trailerPresenceIsUnknown , 
            [ASN1EnumItem ( Name = "unavailable", HasTag = true , Tag = 4 )]
            unavailable , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(VehicleLengthConfidenceIndication));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }


    }
            
}
