
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "VehicleRole", IsExtensible = false, NumRootElements = 16)]
    public class VehicleRole : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "default", HasTag = true , Tag = 0 )]
            Default , 
            [ASN1EnumItem ( Name = "publicTransport", HasTag = true , Tag = 1 )]
            PublicTransport , 
            [ASN1EnumItem ( Name = "specialTransport", HasTag = true , Tag = 2 )]
            SpecialTransport , 
            [ASN1EnumItem ( Name = "dangerousGoods", HasTag = true , Tag = 3 )]
            DangerousGoods , 
            [ASN1EnumItem ( Name = "roadWork", HasTag = true , Tag = 4 )]
            RoadWork , 
            [ASN1EnumItem ( Name = "rescue", HasTag = true , Tag = 5 )]
            Rescue , 
            [ASN1EnumItem ( Name = "emergency", HasTag = true , Tag = 6 )]
            Emergency , 
            [ASN1EnumItem ( Name = "safetyCar", HasTag = true , Tag = 7 )]
            SafetyCar , 
            [ASN1EnumItem ( Name = "agriculture", HasTag = true , Tag = 8 )]
            Agriculture , 
            [ASN1EnumItem ( Name = "commercial", HasTag = true , Tag = 9 )]
            Commercial , 
            [ASN1EnumItem ( Name = "military", HasTag = true , Tag = 10 )]
            Military , 
            [ASN1EnumItem ( Name = "roadOperator", HasTag = true , Tag = 11 )]
            RoadOperator , 
            [ASN1EnumItem ( Name = "taxi", HasTag = true , Tag = 12 )]
            Taxi , 
            [ASN1EnumItem ( Name = "reserved1", HasTag = true , Tag = 13 )]
            Reserved1 , 
            [ASN1EnumItem ( Name = "reserved2", HasTag = true , Tag = 14 )]
            Reserved2 , 
            [ASN1EnumItem ( Name = "reserved3", HasTag = true , Tag = 15 )]
            Reserved3 , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(VehicleRole));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }


    }
            
}
