
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "VehicleLength", IsExtensible = false, IsSet = false)]
    public class VehicleLength : IASN1PreparedElement {
                
	private VehicleLengthValue vehicleLengthValue_ ;
	
        [ASN1Element ( Name = "vehicleLengthValue", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public VehicleLengthValue VehicleLengthValue
        {
            get { return vehicleLengthValue_; }
            set { vehicleLengthValue_ = value;  }
        }
        
                
          
	private VehicleLengthConfidenceIndication vehicleLengthConfidenceIndication_ ;
	
        [ASN1Element ( Name = "vehicleLengthConfidenceIndication", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public VehicleLengthConfidenceIndication VehicleLengthConfidenceIndication
        {
            get { return vehicleLengthConfidenceIndication_; }
            set { vehicleLengthConfidenceIndication_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(VehicleLength));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
