
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "VehicleIdentification", IsExtensible = true, IsSet = false)]
    public class VehicleIdentification : IASN1PreparedElement {
                
	private WMInumber wMInumber_ ;
	
        private bool  wMInumber_present = false ;
	
        [ASN1Element ( Name = "wMInumber", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public WMInumber WMInumber
        {
            get { return wMInumber_; }
            set { wMInumber_ = value; wMInumber_present = true;  }
        }
        
                
          
	private VDS vDS_ ;
	
        private bool  vDS_present = false ;
	
        [ASN1Element ( Name = "vDS", IsOptional =  true , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public VDS VDS
        {
            get { return vDS_; }
            set { vDS_ = value; vDS_present = true;  }
        }
        
                
  
        public bool isWMInumberPresent () {
            return this.wMInumber_present == true;
        }
        
        public bool isVDSPresent () {
            return this.vDS_present == true;
        }
        

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(VehicleIdentification));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
