
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "VerticalAcceleration", IsExtensible = false, IsSet = false)]
    public class VerticalAcceleration : IASN1PreparedElement {
                
	private VerticalAccelerationValue verticalAccelerationValue_ ;
	
        [ASN1Element ( Name = "verticalAccelerationValue", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public VerticalAccelerationValue VerticalAccelerationValue
        {
            get { return verticalAccelerationValue_; }
            set { verticalAccelerationValue_ = value;  }
        }
        
                
          
	private AccelerationConfidence verticalAccelerationConfidence_ ;
	
        [ASN1Element ( Name = "verticalAccelerationConfidence", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public AccelerationConfidence VerticalAccelerationConfidence
        {
            get { return verticalAccelerationConfidence_; }
            set { verticalAccelerationConfidence_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(VerticalAcceleration));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
