
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "YawRate", IsExtensible = false, IsSet = false)]
    public class YawRate : IASN1PreparedElement {
                
	private YawRateValue yawRateValue_ ;
	
        [ASN1Element ( Name = "yawRateValue", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public YawRateValue YawRateValue
        {
            get { return yawRateValue_; }
            set { yawRateValue_ = value;  }
        }
        
                
          
	private YawRateConfidence yawRateConfidence_ ;
	
        [ASN1Element ( Name = "yawRateConfidence", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public YawRateConfidence YawRateConfidence
        {
            get { return yawRateConfidence_; }
            set { yawRateConfidence_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(YawRate));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
