
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "YawRateConfidence", IsExtensible = false, NumRootElements = 9)]
    public class YawRateConfidence : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "degSec-000-01", HasTag = true , Tag = 0 )]
            degSec_000_01 , 
            [ASN1EnumItem ( Name = "degSec-000-05", HasTag = true , Tag = 1 )]
            degSec_000_05 , 
            [ASN1EnumItem ( Name = "degSec-000-10", HasTag = true , Tag = 2 )]
            degSec_000_10 , 
            [ASN1EnumItem ( Name = "degSec-001-00", HasTag = true , Tag = 3 )]
            degSec_001_00 , 
            [ASN1EnumItem ( Name = "degSec-005-00", HasTag = true , Tag = 4 )]
            degSec_005_00 , 
            [ASN1EnumItem ( Name = "degSec-010-00", HasTag = true , Tag = 5 )]
            degSec_010_00 , 
            [ASN1EnumItem ( Name = "degSec-100-00", HasTag = true , Tag = 6 )]
            degSec_100_00 , 
            [ASN1EnumItem ( Name = "outOfRange", HasTag = true , Tag = 7 )]
            outOfRange , 
            [ASN1EnumItem ( Name = "unavailable", HasTag = true , Tag = 8 )]
            unavailable , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(YawRateConfidence));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }


    }
            
}
