
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace its.cam {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "YawRateValue" )]
    public class YawRateValue: IASN1PreparedElement {
    
            private int val;
            
            [ASN1Integer( Name = "YawRateValue" )]
            [ASN1ValueRangeConstraint ( Min = -32766L, Max = 32767L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public YawRateValue() {
            }

            public YawRateValue(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(YawRateValue));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
