
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace org.bn.coders.test_asn {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "DataSeqExtensible", IsExtensible = true, IsSet = false)]
    public class DataSeqExtensible : IASN1PreparedElement {
                
	private int simpleInt_ ;
	[ASN1Integer( Name = "" )]
    [ASN1ValueRangeConstraint ( Min = 0L, Max = 255L, IsExtensible = false) ]
	    
        [ASN1Element ( Name = "simpleInt", IsOptional =  false , IsExtended =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public int SimpleInt
        {
            get { return simpleInt_; }
            set { simpleInt_ = value;  }
        }
        
                
          
	private bool simpleBool_ ;
	[ASN1Boolean( Name = "" )]
    
        [ASN1Element ( Name = "simpleBool", IsOptional =  false , IsExtended =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public bool SimpleBool
        {
            get { return simpleBool_; }
            set { simpleBool_ = value;  }
        }
        
                
          
	private bool optBool_ ;
	
        private bool  optBool_present = false ;
	[ASN1Boolean( Name = "" )]
    
        [ASN1Element ( Name = "optBool", IsOptional =  true , IsExtended =  false , HasTag =  true, Tag = 2 , HasDefaultValue =  false )  ]
    
        public bool OptBool
        {
            get { return optBool_; }
            set { optBool_ = value; optBool_present = true;  }
        }
        
                
          
	private int extendedInt1_ ;
	
        private bool  extendedInt1_present = false ;
	[ASN1Integer( Name = "" )]
    [ASN1ValueRangeConstraint ( Min = 0L, Max = 63L, IsExtensible = false) ]
	    
        [ASN1Element ( Name = "extendedInt1", IsOptional =  true , IsExtended =  true , HasTag =  true, Tag = 3 , HasDefaultValue =  false )  ]
    
        public int ExtendedInt1
        {
            get { return extendedInt1_; }
            set { extendedInt1_ = value; extendedInt1_present = true;  }
        }
        
                
          
	private int extendedInt2_ ;
	[ASN1Integer( Name = "" )]
    [ASN1ValueRangeConstraint ( Min = 0L, Max = 100000L, IsExtensible = false) ]
	    
        [ASN1Element ( Name = "extendedInt2", IsOptional =  false , IsExtended =  true , HasTag =  true, Tag = 4 , HasDefaultValue =  false )  ]
    
        public int ExtendedInt2
        {
            get { return extendedInt2_; }
            set { extendedInt2_ = value;  }
        }
        
                
  
        public bool isOptBoolPresent () {
            return this.optBool_present == true;
        }
        
        public bool isExtendedInt1Present () {
            return this.extendedInt1_present == true;
        }
        

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DataSeqExtensible));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
