
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace org.bn.coders.test_asn {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "ExtendedChoiceSeq", IsExtensible = false, IsSet = false)]
    public class ExtendedChoiceSeq : IASN1PreparedElement {
                
	private ChoiceType choi_ ;
	
        [ASN1Element ( Name = "choi", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public ChoiceType Choi
        {
            get { return choi_; }
            set { choi_ = value;  }
        }
        
                
          
	private int tail_ ;
	[ASN1Integer( Name = "" )]
    [ASN1ValueRangeConstraint ( Min = 0L, Max = 255L, IsExtensible = false) ]
	    
        [ASN1Element ( Name = "tail", IsOptional =  false , IsExtended =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public int Tail
        {
            get { return tail_; }
            set { tail_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ExtendedChoiceSeq));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }

    }
            
}
