
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace org.bn.coders.test_asn {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "ExtensibleInteger" )]
    public class ExtensibleInteger: IASN1PreparedElement {
    
            private int val;
            
            [ASN1Integer( Name = "ExtensibleInteger" )]
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 63L, IsExtensible = true) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public ExtensibleInteger() {
            }

            public ExtensibleInteger(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ExtensibleInteger));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
