
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace org.bn.coders.test_asn {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "MixedEnumType", IsExtensible = false, NumRootElements = 3)]
    public class MixedEnumType : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "low", HasTag = true , Tag = 3 )]
            low , 
            [ASN1EnumItem ( Name = "mid", HasTag = true , Tag = 8 )]
            mid , 
            [ASN1EnumItem ( Name = "high", HasTag = true , Tag = 101 )]
            high , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }

        public void initWithDefaults()
        {
        }


        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(MixedEnumType));
            public IASN1PreparedElementData PreparedData {
            get { return preparedData; }
        }


    }
            
}
