
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace org.bn.coders.test_asn {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "TestI8named" )]
    public class TestI8named: IASN1PreparedElement {
            
            public static readonly TestI8named A = new(1);
            public static readonly TestI8named B = new(2);
            public static readonly TestI8named D = new(5);

            private int val;

            [ASN1Integer( Name = "TestI8named" )]
            [ASN1ValueRangeConstraint ( Min = 0L, Max = 253L, IsExtensible = false) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public TestI8named() {
            }

            public TestI8named(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(TestI8named));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
